### ISSUE TITLE
Design initial data schema

### ISSUE THREAD

**Issue by IgorGee** [hunter695/icebreaker-client#3]

**Comment by jurddle** [comment]
Schema designed and inserted into database.

**Comment by IgorGee** [comment]
Where?

Don't close the issue unless you refer to the commit or at the very least post a comment of the schema.

**Comment by IgorGee** [comment]
Issue moved to [hunter695/icebreaker-api #3](https://github.com/hunter695/icebreaker-api/issues/3) via [**ZenHub**](https://www.zenhub.com/)
