### ISSUE TITLE
Create tweet retrieval service

### ISSUE THREAD

**Issue by IgorGee** [hunter695/icebreaker-client#7]
Features to include:

* retrieve tweets with a given hashtag
* retrieve the tweets within a timeframe

**Comment by jurddle** [comment]
created function to get tweets and insert into DB, however must check why certain hashtags won't work.

**Comment by IgorGee** [comment]
Again, don't close unless you refer to a commit.

**Comment by IgorGee** [comment]
Issue moved to [hunter695/icebreaker-api #4](https://github.com/hunter695/icebreaker-api/issues/4) via [**ZenHub**](https://www.zenhub.com/)
